import Head from "next/head";
import GoogleLogin from "react-google-login";

export default function Home({GOOGLE_CLIENT_ID}) {
  const handleLogin = async (googleData) => {
    // fetch to our server REST API for confirmation and create new user and login eventually
    const res = await fetch("http://localhost:8000/api/v1/user/google", {
      method: "POST",
      body: JSON.stringify({
        token: googleData.tokenId, // google signed access token - need server verification
      }),
      headers: {
        "Content-Type": "application/json",
      },
    });

    /**
     * Server request
     * Created User Or Existing User JWT Token
     */
    const data = await res.json(); 
    console.log(data); 

    /** LOCALLY STORE JWT TOKEN*/
  };

  return (
    <div>
      <Head>
        <title>Google Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GoogleLogin
        clientId={GOOGLE_CLIENT_ID}
        buttonText="Log in with Google"
        onSuccess={handleLogin}
        onFailure={handleLogin}
        cookiePolicy={"single_host_origin"}
      />
    </div>
  );
}

export async function getStaticProps(){
  // return props with loaded google client id
  return {
    props : {
      GOOGLE_CLIENT_ID : process.env.GOOGLE_CLIENT_ID // Get client id from environment
    }
  }
}
